@startuml
!theme reddress-darkgreen

class test.A {
aBoolean
aChar
aDouble
aFloat
aByte
aShort
aLong
anInt

}

abstract test.B

class test.C

abstract test.D

abstract test.E

class test.Java2PumlTest1

"test.C" .. "int" : <<Use>>
"test.C" .. "long" : <<Use>>
test.A -- D : <<Use>>
"test.D" .. "test.D" : <<Use>>
"test.D" .. "test.A" : <<Use>>
"test.D" .. "test.A" : <<Use>>
"test.D" .. "test.A" : <<Use>>
"test.D" .. "test.B" : <<Use>>
"test.D" .. "test.C" : <<Use>>

@enduml

