@startuml
!theme reddress-darkgreen

class pumlFromJava.doclets.FirstDoclet

class pumlFromJava.doclets.PumlDoclet

class pumlFromJava.doclets.options.OutOption {
NameFile

}

class pumlFromJava.doclets.options.PathOption {
path

}

class pumlFromJava.doclets.options.TypeOption {
type

}

class pumlFromJava.generators.Java2Puml

class pumlFromJava.translators.diagrams.PumlACD implements pumlFromJava.translators.diagrams.PumlDiagram

class pumlFromJava.translators.diagrams.PumlBasis implements pumlFromJava.translators.diagrams.PumlDiagram

class pumlFromJava.translators.diagrams.PumlCCD implements pumlFromJava.translators.diagrams.PumlDiagram

interface pumlFromJava.translators.diagrams.PumlDiagram
interface pumlFromJava.translators.elements.InheritableObject
interface pumlFromJava.translators.elements.Nameable
interface pumlFromJava.translators.elements.ObjectTranslator extends pumlFromJava.translators.elements.PumlRawObject, pumlFromJava.translators.elements.Nameable
class pumlFromJava.translators.elements.PumlEnum extends pumlFromJava.translators.elements.PumlObject

class pumlFromJava.translators.elements.PumlInterface extends pumlFromJava.translators.elements.PumlObject implements pumlFromJava.translators.elements.InheritableObject

class pumlFromJava.translators.elements.PumlMethod implements pumlFromJava.translators.elements.PumlRawObject, pumlFromJava.translators.elements.Nameable

abstract pumlFromJava.translators.elements.PumlObject implements pumlFromJava.translators.elements.ObjectTranslator

interface pumlFromJava.translators.elements.PumlRawObject
class pumlFromJava.translators.elements.PumlType implements pumlFromJava.translators.elements.PumlRawObject

class pumlFromJava.translators.elements.pumlClasses.PumlClass extends pumlFromJava.translators.elements.pumlClasses.PumlClasses

abstract pumlFromJava.translators.elements.pumlClasses.PumlClasses extends pumlFromJava.translators.elements.PumlObject implements pumlFromJava.translators.elements.InheritableObject, pumlFromJava.translators.elements.pumlRelations.RelationableObject

class pumlFromJava.translators.elements.pumlClasses.PumlLiteClass extends pumlFromJava.translators.elements.pumlClasses.PumlClasses

class pumlFromJava.translators.elements.pumlRelations.PumlArrow {
arrow

}

enum pumlFromJava.translators.elements.pumlRelations.PumlArrowLook {
DOTTED
SOLID
HEADFULL_SOLID
HEADFULL_DOTTED
HEADSOCKET_SOLID
HEADSOCKET_DOTTED
DIAMOND_EMPTY
DIAMOND_FULL

}
interface pumlFromJava.translators.elements.pumlRelations.RelationableObject
class pumlFromJava.translators.elements.tools.TranslatorTools

class pumlFromJava.translators.marker.Marker

class pumlFromJava.translators.viewers.AnnotationsViewer implements pumlFromJava.translators.elements.PumlRawObject

class pumlFromJava.translators.viewers.ModifiersViewer implements pumlFromJava.translators.elements.PumlRawObject

class pumlFromJava.translators.viewers.VisibilityViewer implements pumlFromJava.translators.elements.PumlRawObject

class pumlFromJava.writers.Writer implements pumlFromJava.writers.WriterSpecies {
filepath

}

interface pumlFromJava.writers.WriterSpecies
pumlFromJava.doclets.options.PathOption<--PumlDoclet : <<Use>>
pumlFromJava.doclets.options.OutOption<--PumlDoclet : <<Use>>
pumlFromJava.doclets.options.TypeOption<--PumlDoclet : <<Use>>
pumlFromJava.translators.viewers.VisibilityViewer<--PumlClass : <<Use>>
pumlFromJava.translators.viewers.ModifiersViewer<--PumlClasses : <<Use>>
pumlFromJava.translators.viewers.AnnotationsViewer<--PumlClasses : <<Use>>
pumlFromJava.translators.elements.pumlRelations.PumlArrowLook<--PumlArrow : <<Use>>

@enduml

