@startuml
!theme reddress-darkgreen

class pumlFromJava.diagrams.PumlACD implements pumlFromJava.diagrams.PumlDiagram

class pumlFromJava.diagrams.PumlBasis implements pumlFromJava.diagrams.PumlDiagram

class pumlFromJava.diagrams.PumlCCD implements pumlFromJava.diagrams.PumlDiagram

interface pumlFromJava.diagrams.PumlDiagram
class pumlFromJava.doclets.FirstDoclet

class pumlFromJava.doclets.PumlDoclet

class pumlFromJava.doclets.options.OutOption {
NameFile

}

class pumlFromJava.doclets.options.PathOption {
path

}

class pumlFromJava.doclets.options.TypeOption {
type

}

class pumlFromJava.generators.Java2Puml

abstract pumlFromJava.translators.elements.internals.PumlInternal implements pumlFromJava.translators.elements.internals.RawInternal

class pumlFromJava.translators.elements.internals.PumlMethod implements pumlFromJava.translators.elements.rawObjects.PumlRawObject, pumlFromJava.translators.elements.Nameable

class pumlFromJava.translators.elements.internals.PumlType extends pumlFromJava.translators.elements.internals.PumlInternal

interface pumlFromJava.translators.elements.internals.RawInternal
interface pumlFromJava.translators.elements.Nameable
interface pumlFromJava.translators.elements.rawObjects.InheritableObject
interface pumlFromJava.translators.elements.rawObjects.ObjectTranslator extends pumlFromJava.translators.elements.rawObjects.PumlRawObject, pumlFromJava.translators.elements.Nameable
class pumlFromJava.translators.elements.rawObjects.PumlEnum extends pumlFromJava.translators.elements.rawObjects.PumlObject

class pumlFromJava.translators.elements.rawObjects.PumlInterface extends pumlFromJava.translators.elements.rawObjects.PumlObject implements pumlFromJava.translators.elements.rawObjects.InheritableObject

abstract pumlFromJava.translators.elements.rawObjects.PumlObject implements pumlFromJava.translators.elements.rawObjects.ObjectTranslator

interface pumlFromJava.translators.elements.rawObjects.PumlRawObject
class pumlFromJava.translators.elements.rawObjects.pumlClasses.PumlClass extends pumlFromJava.translators.elements.rawObjects.pumlClasses.PumlClasses

abstract pumlFromJava.translators.elements.rawObjects.pumlClasses.PumlClasses extends pumlFromJava.translators.elements.rawObjects.PumlObject implements pumlFromJava.translators.elements.rawObjects.InheritableObject, pumlFromJava.translators.elements.relations.RelationableObject

class pumlFromJava.translators.elements.rawObjects.pumlClasses.PumlLiteClass extends pumlFromJava.translators.elements.rawObjects.pumlClasses.PumlClasses

class pumlFromJava.translators.elements.relations.PumlArrow {
arrow

}

enum pumlFromJava.translators.elements.relations.PumlArrowLook {
DOTTED
SOLID
HEADFULL_SOLID
HEADFULL_DOTTED
HEADSOCKET_SOLID
HEADSOCKET_DOTTED
DIAMOND_EMPTY
DIAMOND_FULL

}
interface pumlFromJava.translators.elements.relations.RelationableObject
class pumlFromJava.translators.elements.tools.TranslatorTools

class pumlFromJava.translators.marker.Marker

class pumlFromJava.translators.viewers.AnnotationsViewer implements pumlFromJava.translators.elements.rawObjects.PumlRawObject

class pumlFromJava.translators.viewers.ModifiersViewer implements pumlFromJava.translators.elements.rawObjects.PumlRawObject

class pumlFromJava.translators.viewers.VisibilityViewer implements pumlFromJava.translators.elements.rawObjects.PumlRawObject

class pumlFromJava.writers.Writer implements pumlFromJava.writers.WriterSpecies {
filepath

}

interface pumlFromJava.writers.WriterSpecies
pumlFromJava.doclets.options.PathOption<--PumlDoclet : <<Use>>
pumlFromJava.doclets.options.OutOption<--PumlDoclet : <<Use>>
pumlFromJava.doclets.options.TypeOption<--PumlDoclet : <<Use>>
pumlFromJava.translators.viewers.VisibilityViewer<--PumlClass : <<Use>>
pumlFromJava.translators.viewers.ModifiersViewer<--PumlClasses : <<Use>>
pumlFromJava.translators.viewers.AnnotationsViewer<--PumlClasses : <<Use>>
pumlFromJava.translators.elements.relations.PumlArrowLook<--PumlArrow : <<Use>>

@enduml

