@startuml
!theme reddress-darkgreen

class test.A {
~ <<create>> A()
+ {static} aBoolean : Boolean
~ {static} aChar : Char
# {static}  {readonly} aDouble : double
-aFloat : Float
+aByte : byte
# {readonly} aShort : short
~aLong : long
-anInt : Integer
- {static}   aFloatFunction(aFloatParam : Float) : Float
# {static}  {readonly}   aDoubleFunction(aDoubleParam : double) : double
~ {static}   aCharFunction(aCharParam : Char) : Char
+ {static}   aBooleanFunction(aBooleanParam : Boolean) : Boolean
-  anIntFunction(anIntParam : Integer) : Integer
# {readonly}   aShortFunction(aShortParam : short) : short
~  aLongFunction(aLongParam : long) : long
+  aByteFunction(aByteParam : byte) : byte

}
abstract test.B {
~ <<create>> B()
~ {static}   aCharacterFunction(aCharacterParam : Character) : Character
+ {static}   aBooleanFunction(aBooleanParam : Boolean) : Boolean
-  anIntFunction(anIntParam : Integer) : Integer
# {readonly}   aShortFunction(aShortParam : Short) : Short
~  aLongFunction(aLongParam : Long) : Long
+  aByteFunction(aByteParam : Byte) : Byte
-  aFloatFunction(aFloatParam : Float) : Float
# {abstract}  {readonly}   aDoubleFunction(aDoubleParam : Double) : Double

}
class test.C {
~ <<create>> C()
-  anIntArrayFunction(anIntArrayParam : int[*]) : int[*]
# {readonly}   aShortArrayFunction(aShortArrayParam : Short[*]) : Short[*]
~  aLong3DArrayFunction(someLongs : long[*]) : long[*]
+  aByte5DArrayFunction(someBytes : Byte[*]) : Byte[*]
-  aFloatListFunction(aFloatListParam : Float[*]) : Float[*]
# {readonly}   aListOfDoubleListFunction(someDoubles : Double[*]) : Double[*]
~  aCharacterSetFunction(aCharacterSetParam : Character[*]) : Character[*]
+  aSetOfBooleanListFunction(someBooleans : Boolean[*]) : Boolean[*]

}
abstract test.D {
~ <<create>> D()
+ {static}   dFunction(d0 : D, d1 : D[*], d2 : D[*], d3 : D[*], d4 : D[*]) : D[*]
-  aFunction(a0 : A, a1 : A[*], a2 : A[*], a3 : A[*]) : A
~  bFunction(b0 : B, b1 : B[*], b2 : B[*], b3 : B[*]) : B[*]
# {abstract}  {readonly}   cFunction(c0 : C, c1 : C[*], c2 : C[*], c3 : C[*]) : C[*]

}
abstract test.E {
~ <<create>> E()
+ {static}   mapOfArrayOfAFunction(a0 : A[*], a1 : A[*], a2 : A[*], a3 : A[*]) : A[*]
-  mapOfIntFunction(a0 : Integer[*], a1 : Integer[*], a2 : Integer[*], a3 : Integer[*]) : Integer[*]
~ {abstract}   mapOfDoubleArrayFunction(a0 : Double[*], a1 : Double[*], a2 : Double[*], a3 : Double[*]) : Double[*]
# {readonly}   mapOfAFunction(a0 : A[*], a1 : A[*], a2 : A[*], a3 : A[*]) : A[*]

}
class test.Java2PumlTest1 {
+ <<create>> Java2PumlTest1()

}
"test.C""1" <.. "1""int" : <<Use>>
"test.C""1" <.. "1""long" : <<Use>>
test.A"1" <--o "1"D : -a
"test.D""1" <.. "1""test.D" : <<Use>>
"test.D""1" <.. "1""test.A" : <<Use>>
"test.D""1" <.. "1""test.A" : <<Use>>
"test.D""1" <.. "1""test.A" : <<Use>>
"test.D""1" <.. "1""test.B" : <<Use>>
"test.D""1" <.. "1""test.C" : <<Use>>

@enduml

