@startuml
!theme reddress-darkgreen
skinparam style strictuml

package western {
class Barman extends western.Personnage {

}
class Boisson {

}
class Brigand extends western.Personnage {
recompense
estLibre

}
class Cowboy extends western.Personnage {
gains

}
class Dame extends western.Personnage {
estLibre

}
enum Genre <<enumeration>> {
FEMININ
MASCULIN

}
class Histoire4 {

}
class Histoire5 {

}
interface HorsLaLoi <<interface>>
class Narrateur extends western.Personnage {

}
interface Nommable <<interface>>
class Personnage {

}
class Ripou extends western.Cowboy {

}
class Sherif extends western.Cowboy {

}
class Substantif {

}

@enduml

