@startuml
!theme reddress-darkgreen

/' Note :
 - PrintWriter est un equivalent à la classe d'écriture de fichier
 de Csharp
 - Des paramètres du type int... ou String... (avec les "...") servent
 à créer automatiquement un tableau adapté au nombre d'argument de ce type.
 Autrement dit : que l'on passe 1, 5 ou 10000 arguments, un tableau de la
 bonne taille sera passé à la fonction.
 '/


interface Doclet {
}
/' dans l'interface Doclet '/
interface Option {
}
/' dans l'interface Option '/
enum Kind {
    EXTENDED
    STANDARD
    OTHER
}

interface DocletEnvironment {

}
/' dans l'interface DocletEnvironment '/
enum ModuleMode {
    API
    ALL
}


class Java2Puml {
    + {static} main(args : String[])
}
class ToolProvider {
}
class FirstDoclet implements Doclet {
}
class Javadoc {

}
class System.out {}


Java2Puml o- ToolProvider
Javadoc o- FirstDoclet
Java2Puml -- System.out : <<Use>>
FirstDoclet -- System.out : <<Use>>
FirstDoclet -- DocletEnvironment : <<Use>>
Doclet *- Option
Option *- Kind
DocletEnvironment *- ModuleMode

@enduml