@startuml
!theme reddress-darkgreen

/' Note :
 - PrintWriter est un equivalent à la classe d'écriture de fichier
 de Csharp
 - Des paramètres du type int... ou String... (avec les "...") servent
 à créer automatiquement un tableau adapté au nombre d'argument de ce type.
 Autrement dit : que l'on passe 1, 5 ou 10000 arguments, un tableau de la
 bonne taille sera passé à la fonction.
 '/


interface Doclet {
    + getSupportedOptions()
    + getSupportedSourceVersion()
    + getName()
    + run(environment : DocletEnvironment)
    - init(locale : Locale, reporter : Reporter)
}
/' dans l'interface Doclet '/
interface Option {
        +getArgumentCount() : Integer
        +getDescription() : String
        +getKind() : Option.Kind
        +getNames() : List<String>
        +getParameters() : String
        +process(String option, List<String> arguments) : boolean
}
/' dans l'interface Option '/
enum Kind {
    EXTENDED
    STANDARD
    OTHER
}

interface DocletEnvironment {
    + getSpecifiedElements() : Set<? extends Element>
    + getIncludedElements() : Set<? extends Element>
    + getDocTrees() : DocTrees
    + getElementUtils() : Elements
    + getTypeUtils() : Types
    + isIncluded(e : Element) : boolean
    + isSelected(e : Element) : boolean
    + getJavaFileManager() : JavaFileManager
    + getSourceVersion() : SourceVersion
    + getModuleMode() : ModuleMode
    + getFileKind(type : TypeElement) : Kind
}
/' dans l'interface DocletEnvironment '/
enum ModuleMode {
    API
    ALL
}


class Java2Puml {
    + {static} main(args : String[])
}
class ToolProvider {
    + name() : String
    + description() : Optional<String
    + run(out : PrintWriter, err : PrintWriter, args : String...) : Integer
    + {static} findFirst(name : String) : Optional<ToolProvider>
}
class FirstDoclet implements Doclet {
    + <<Create>> Doclet()
    + getSupportedOptions()
    + getSupportedSourceVersion()
    + getName()
    + run(environment : DocletEnvironment)
    - init(locale : Locale, reporter : Reporter)
}
class Javadoc {

}
class System.out {}


Java2Puml o- ToolProvider
Javadoc o- FirstDoclet
Java2Puml -- System.out : <<Use>>
FirstDoclet -- System.out : <<Use>>
FirstDoclet -- DocletEnvironment : <<Use>>
Doclet *- Option
Option *- Kind
DocletEnvironment *- ModuleMode

@enduml