@startuml
!theme reddress-darkgreen
skinparam style strictuml

legend top
Sequence Diagram of Javadoc run
end legend

participant "System.out" as sout

create "Java2Puml" as jp
[o-> jp : main(args)
activate jp

create "toolProvider : ToolProvider" as tp /' compilateur '/
jp -> tp : <<Create>>
activate tp

create "ToolProvider.class" as mtp
tp -> mtp : findFirst("javadoc").get()
activate mtp
return get()
jp -> sout : println(toolProvider.name())
jp -> tp : run(System.out, System.err, args)

create "Javadoc" as jd
tp -> jd : run()
activate jd

create "FirstDoclet" as fd
jd -> fd : run(environment : DocletEnvironment)
activate fd
participant "System.out" as sout
fd -> fd : getName()
fd -> sout : println(getName()
fd -> sout : println(environment.getSpecifiedElements())
fd -> sout : println(environment.getIncludedElements())
loop
fd -> fd : dumpElement(element)
end loop
return true
return
return
/' end '/

@enduml